<?php
/**
 * Curated Font Awesome Icons for Redux Framework
 * Includes 100 most useful FREE icons (v6.4.0)
 */
return array(
    // ============ General UI ============
    'fas fa-check'               => 'Check',
    'fas fa-check-circle'        => 'Check Circle',
    'fas fa-times'               => 'Times',
    'fas fa-times-circle'        => 'Times Circle',
    'fas fa-info-circle'         => 'Info',
    'fas fa-exclamation-circle'  => 'Exclamation',
    'fas fa-question-circle'     => 'Question',
    'fas fa-cog'                 => 'Cog (Settings)',
    'fas fa-sliders-h'           => 'Sliders',
    'fas fa-wrench'              => 'Wrench',

    // ============ Arrows & Navigation ============
    'fas fa-arrow-right'         => 'Arrow Right',
    'fas fa-arrow-left'          => 'Arrow Left',
    'fas fa-arrow-up'            => 'Arrow Up',
    'fas fa-arrow-down'          => 'Arrow Down',
    'fas fa-chevron-right'       => 'Chevron Right',
    'fas fa-chevron-left'        => 'Chevron Left',
    'fas fa-long-arrow-alt-right'=> 'Long Arrow Right',
    'fas fa-exchange-alt'        => 'Exchange',
    'fas fa-expand'              => 'Expand',
    'fas fa-compress'            => 'Compress',

    // ============ Business & Finance ============
    'fas fa-briefcase'           => 'Briefcase',
    'fas fa-chart-line'          => 'Chart Line',
    'fas fa-chart-pie'           => 'Chart Pie',
    'fas fa-dollar-sign'         => 'Dollar',
    'fas fa-euro-sign'           => 'Euro',
    'fas fa-pound-sign'          => 'Pound',
    'fas fa-handshake'           => 'Handshake',
    'fas fa-lightbulb'           => 'Lightbulb',
    'fas fa-rocket'              => 'Rocket',
    'fas fa-trophy'              => 'Trophy',

    // ============ Communication ============
    'fas fa-envelope'            => 'Envelope',
    'fas fa-envelope-open'       => 'Envelope Open',
    'fas fa-comment'             => 'Comment',
    'fas fa-comments'            => 'Comments',
    'fas fa-phone'               => 'Phone',
    'fas fa-phone-alt'           => 'Phone Alt',
    'fas fa-mail-bulk'           => 'Mail Bulk',
    'fas fa-bell'                => 'Bell',
    'fas fa-bell-slash'          => 'Bell Slashed',
    'fas fa-rss'                 => 'RSS',

    // ============ Technology ============
    'fas fa-code'                => 'Code',
    'fas fa-laptop-code'         => 'Laptop Code',
    'fas fa-server'              => 'Server',
    'fas fa-database'            => 'Database',
    'fas fa-microchip'           => 'Microchip',
    'fas fa-mobile-alt'          => 'Mobile',
    'fas fa-tablet-alt'          => 'Tablet',
    'fas fa-desktop'             => 'Desktop',
    'fas fa-hdd'                 => 'HDD',
    'fas fa-keyboard'            => 'Keyboard',

    // ============ People ============
    'fas fa-user'                => 'User',
    'fas fa-user-tie'            => 'User Tie',
    'fas fa-users'               => 'Users',
    'fas fa-user-plus'           => 'User Add',
    'fas fa-user-minus'          => 'User Remove',
    'fas fa-user-cog'            => 'User Cog',
    'fas fa-child'               => 'Child',
    'fas fa-users-cog'           => 'Users Cog',
    'fas fa-id-card'             => 'ID Card',
    'fas fa-id-card-alt'         => 'ID Card Alt',

    // ============ Health ============
    'fas fa-heart'               => 'Heart',
    'fas fa-heartbeat'           => 'Heartbeat',
    'fas fa-medkit'              => 'Medkit',
    'fas fa-ambulance'           => 'Ambulance',
    'fas fa-hospital'            => 'Hospital',
    'fas fa-pills'               => 'Pills',
    'fas fa-prescription-bottle' => 'Prescription',
    'fas fa-stethoscope'         => 'Stethoscope',
    'fas fa-user-md'             => 'Doctor',
    'fas fa-procedures'          => 'Procedures',

    // ============ Social Brands ============
    'fab fa-facebook'            => 'Facebook',
    'fab fa-twitter'             => 'Twitter',
    'fab fa-linkedin'            => 'LinkedIn',
    'fab fa-instagram'           => 'Instagram',
    'fab fa-youtube'             => 'YouTube',
    'fab fa-wordpress'           => 'WordPress',
    'fab fa-google'              => 'Google',
    'fab fa-apple'               => 'Apple',
    'fab fa-android'             => 'Android',
    'fab fa-github'              => 'GitHub',

    // ============ Creative ============
    'fas fa-paint-brush'         => 'Paint Brush',
    'fas fa-palette'             => 'Palette',
    'fas fa-camera'              => 'Camera',
    'fas fa-camera-retro'        => 'Camera Retro',
    'fas fa-film'                => 'Film',
    'fas fa-music'               => 'Music',
    'fas fa-headphones'          => 'Headphones',
    'fas fa-book'                => 'Book',
    'fas fa-book-open'           => 'Book Open',
    'fas fa-pen-fancy'           => 'Pen Fancy',
    'fas fa-pencil-alt'          => 'Pencil Alt', 
    // ============== Additional Icons ==============
    'fa-solid fa-shield-halved'           => 'Shield',
    'fas fa-lock' => 'Lock',
    'fas fa-unlock' => 'Unlock',
    'fas fa-eye' => 'Eye',
    'fas fa-eye-slash' => 'Eye Slash',
    'fas fa-trash' => 'Trash',
    'fas fa-trash-alt' => 'Trash Alt',
    'fas fa-edit' => 'Edit',
    'fas fa-copy' => 'Copy',
    'fas fa-save' => 'Save',
    'fas fa-print' => 'Print',
    'fas fa-search' => 'Search',
    'fas fa-search-plus' => 'Search Plus',
    'fas fa-search-minus' => 'Search Minus',
    'fas fa-calendar' => 'Calendar',
    'fas fa-calendar-alt' => 'Calendar Alt',
    'fas fa-clock' => 'Clock',
    'fas fa-globe' => 'Globe',
    'fas fa-map' => 'Map',
    'fas fa-map-marker-alt' => 'Map Marker',
    'fas fa-compass' => 'Compass',
    'fas fa-star' => 'Star',
    'fas fa-star-half' => 'Star Half',
    'fas fa-star-half-alt' => 'Star Half Alt',
    'fas fa-fire' => 'Fire',
    'fas fa-snowflake' => 'Snowflake',
    'fas fa-cloud' => 'Cloud',
    'fas fa-cloud-download-alt' => 'Cloud Download',
    'fas fa-cloud-upload-alt' => 'Cloud Upload',
    'fas fa-bug' => 'Bug',
    'fas fa-bolt' => 'Bolt',
    'fas fa-sync' => 'Sync',
    'fas fa-redo' => 'Redo',
    'fas fa-undo' => 'Undo',
    'fas fa-plug' => 'Plug',
    'fas fa-battery-full' => 'Battery Full',
    'fas fa-battery-half' => 'Battery Half',
    'fas fa-battery-empty' => 'Battery Empty',
    'fas fa-wifi' => 'WiFi',
    'fas fa-paperclip' => 'Paperclip',
    'fas fa-paper-plane' => 'Paper Plane',
    'fas fa-flag' => 'Flag',
    'fas fa-tags' => 'Tags',
    'fas fa-tag' => 'Tag',
    'fas fa-gift' => 'Gift',
    'fas fa-shopping-cart' => 'Shopping Cart',
    'fas fa-store' => 'Store',
    'fas fa-box' => 'Box',
    'fas fa-cube' => 'Cube',
    'fas fa-truck' => 'Truck',
    'fas fa-plus' => 'Plus',
    'fas fa-minus' => 'Minus',
    'fas fa-check-double' => 'Check Double',
    'fas fa-ellipsis-h' => 'Ellipsis Horizontal',
    'fas fa-ellipsis-v' => 'Ellipsis Vertical',
    'fas fa-bars' => 'Bars',
    'fas fa-th' => 'Thumbnails',
    'fas fa-th-large' => 'Thumbnails Large',
    'fas fa-th-list' => 'Thumbnails List',
    'fas fa-caret-up' => 'Caret Up',
    'fas fa-caret-down' => 'Caret Down',
    'fas fa-caret-left' => 'Caret Left',
    'fas fa-caret-right' => 'Caret Right',
    'fas fa-image' => 'Image',
    'fas fa-images' => 'Images',
    'fas fa-video' => 'Video',
    'fas fa-file' => 'File',
    'fas fa-file-alt' => 'File Alt',
    'fas fa-file-download' => 'File Download',
    'fas fa-file-upload' => 'File Upload',
    'fas fa-folder' => 'Folder',
    'fas fa-folder-open' => 'Folder Open',
    'fas fa-archive' => 'Archive',
    'fas fa-credit-card' => 'Credit Card',
    'fas fa-receipt' => 'Receipt',
    'fas fa-cash-register' => 'Cash Register',
    'fas fa-wallet' => 'Wallet',
    'fas fa-percentage' => 'Percentage',
    'fas fa-coins' => 'Coins',
    'fas fa-piggy-bank' => 'Piggy Bank',
    'fas fa-plane' => 'Plane',
    'fas fa-plane-departure' => 'Plane Departure',
    'fas fa-plane-arrival' => 'Plane Arrival',
    'fas fa-suitcase' => 'Suitcase',
    'fas fa-taxi' => 'Taxi',
    'fas fa-bus' => 'Bus',
    'fas fa-subway' => 'Subway',
    'fas fa-train' => 'Train',
    'fas fa-ship' => 'Ship',
    'fas fa-road' => 'Road',
    'fas fa-hotel' => 'Hotel',
    'fas fa-graduation-cap' => 'Graduation Cap',
    'fas fa-school' => 'School',
    'fas fa-chalkboard-teacher' => 'Chalkboard Teacher',
    'fas fa-book-reader' => 'Book Reader',
    'fas fa-fingerprint' => 'Fingerprint',
    'fas fa-key' => 'Key',
    'fas fa-passport' => 'Passport',
    'fas fa-user-shield' => 'User Shield',
    'fas fa-anchor' => 'Anchor',
    'fas fa-fan' => 'Fan',
    'fas fa-feather' => 'Feather',
    'fas fa-leaf' => 'Leaf',
    'fas fa-tree' => 'Tree',
    'fas fa-recycle' => 'Recycle',
    'fas fa-broom' => 'Broom',
    'fas fa-hammer' => 'Hammer',
    'fa-regular fa-circle-user' => 'user-circle',
    'fa-regular fa-circle-check' => 'check-circle',
    'fa-regular fa-circle-xmark' => 'times-circle',
    'fa-regular fa-circle-question' => 'question-circle',
    'fa-brands fa-whatsapp' => 'WhatsApp',
    'fa-brands fa-telegram' => 'Telegram',
    'fa-brands fa-discord' => 'Discord',
    'fa-brands fa-slack' => 'Slack',
    'fa-brands fa-pinterest' => 'Pinterest',
    'fa-brands fa-tiktok' => 'TikTok',
    'fa-brands fa-snapchat' => 'Snapchat',
    'fa-brands fa-reddit' => 'Reddit',
    'fa-brands fa-quora' => 'Quora',
    'fa-brands fa-vimeo' => 'Vimeo',
    'fa-brands fa-flickr' => 'Flickr',
    'fa-brands fa-yahoo' => 'Yahoo',
    'fa-brands fa-tumblr' => 'Tumblr',
    'fa-brands fa-medium' => 'Medium',
    'fa-brands fa-stack-overflow' => 'Stack Overflow',
    'fa-brands fa-gitlab' => 'GitLab',
    'fa-brands fa-bitbucket' => 'Bitbucket',
    'fa-brands fa-dribbble' => 'Dribbble',
    'fa-brands fa-behance' => 'Behance',
    'fa-brands fa-deviantart' => 'DeviantArt',
);